### ISSUE TITLE
enhancement: Add a LICENSE

### ISSUE THREAD

**Issue by dstaley** [jcbastosportela/logioptspp#11]
Hello! Thank for you sharing this project; it's super useful, and a really clever way to get smooth scrolling working in more applications.

I've been working on a small fork of this that makes some different choices in the name of simplicity, and I'd love to open source those. If you're open to that, would you mind adding a LICENSE to the repo? Detours uses the [MIT License](https://github.com/microsoft/Detours/blob/main/LICENSE) so that might be a good one to go with, but I honestly don't mind which you go with as I'm happy to share my code under the same terms.

Thanks again!

**Comment by jcbastosportela** [comment]
It is great someone is trying to put this for a better and more generic purpose. I currently don't have the time to do it.

As soon as I sit on my laptop I will add some permissive license, probably MIT.

**Comment by jcbastosportela** [comment]
Done
