### ISSUE TITLE
Build instructions/Init release?

### ISSUE THREAD

**Issue by bonzibudd** [jcbastosportela/logioptspp#3]
Could you provide some basic info on building the program or provide a built release? (Haven't used Visual Studio in a while so I apologize if it's a stupid question)

**Comment by jcbastosportela** [comment]
> Could you provide some basic info on building the program or provide a built release? (Haven't used Visual Studio in a while so I apologize if it's a stupid question)

Will clean the code, make it configurable and make a release after my holiday. Mid September

**Comment by jcbastosportela** [comment]
> Could you provide some basic info on building the program or provide a built release? (Haven't used Visual Studio in a while so I apologize if it's a stupid question)

try this:
https://github.com/jcbastosportela/logioptspp/releases/download/v0.0.1/v0.0.1.zip

**Comment by bonzibudd** [comment]
Just tried this out, seems to be working amazingly! I haven't tried blacklisting anything but I'll check that out at some point soon.

Thank you so much for this btw, this is actually a game changer since I do a lot of audio production and this works perfectly with the DAW I am using.
